# =========================================================
# DOCKER COMPOSE PARA PRODUCCIÓN EN HETZNER
# =========================================================

version: '3.8'

services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-stock-ocr-prod
    ports:
      - "8000:8000"
    environment:
      # Autenticación (CAMBIAR EN PRODUCCIÓN)
      - OCR_BASIC_AUTH_USER=${OCR_BASIC_AUTH_USER:-ocr_production}
      - OCR_BASIC_AUTH_PASS=${OCR_BASIC_AUTH_PASS:-change_this_password}
      
      # URLs de callback producción
      - CALLBACK_BASE_URL=${CALLBACK_BASE_URL:-https://sistema-stock.vercel.app}
      - CALLBACK_SECRET=${CALLBACK_SECRET:-change_this_secret}
      
      # Configuración OCR
      - PADDLE_OCR_LANG=es
      - MAX_IMAGE_SIZE_MB=15
      
      # Optimización producción
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    volumes:
      # Persistir modelos OCR
      - ocr-models-prod:/home/ocruser/.paddleocr
      # Logs persistentes
      - ./logs:/tmp/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s
    
    restart: always
    
    # Recursos para producción
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 1.5G
          cpus: '1.0'
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ocr-models-prod:
    driver: local

# =========================================================
# COMANDOS PARA PRODUCCIÓN
# =========================================================
#
# Configurar variables:
# cp .env.example .env
# nano .env
#
# Levantar en producción:
# docker-compose -f docker-compose.prod.yml up -d
#
# Ver logs:
# docker-compose -f docker-compose.prod.yml logs -f
#
# Actualizar servicio:
# docker-compose -f docker-compose.prod.yml pull
# docker-compose -f docker-compose.prod.yml up -d
#
# =========================================================